// flow-typed signature: 9d80b714e299cda9ae04cbabb40112fc
// flow-typed version: <<STUB>>/@dosomething/babel-config_v^2.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dosomething/babel-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dosomething/babel-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@dosomething/babel-config/index' {
  declare module.exports: $Exports<'@dosomething/babel-config'>;
}
declare module '@dosomething/babel-config/index.js' {
  declare module.exports: $Exports<'@dosomething/babel-config'>;
}
