// flow-typed signature: 655e812862f56264cb39b1b74efcc0b5
// flow-typed version: <<STUB>>/@dosomething/eslint-config_v^3.1.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dosomething/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dosomething/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dosomething/eslint-config/nodejs/6.x' {
  declare module.exports: any;
}

declare module '@dosomething/eslint-config/nodejs/8.x' {
  declare module.exports: any;
}

declare module '@dosomething/eslint-config/nodejs/ava' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dosomething/eslint-config/index' {
  declare module.exports: $Exports<'@dosomething/eslint-config'>;
}
declare module '@dosomething/eslint-config/index.js' {
  declare module.exports: $Exports<'@dosomething/eslint-config'>;
}
declare module '@dosomething/eslint-config/nodejs/6.x.js' {
  declare module.exports: $Exports<'@dosomething/eslint-config/nodejs/6.x'>;
}
declare module '@dosomething/eslint-config/nodejs/8.x.js' {
  declare module.exports: $Exports<'@dosomething/eslint-config/nodejs/8.x'>;
}
declare module '@dosomething/eslint-config/nodejs/ava.js' {
  declare module.exports: $Exports<'@dosomething/eslint-config/nodejs/ava'>;
}
