// flow-typed signature: da81cca046fac8e3551c028840733e49
// flow-typed version: <<STUB>>/@dosomething/webpack-config_v^3.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dosomething/webpack-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dosomething/webpack-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@dosomething/webpack-config/index' {
  declare module.exports: $Exports<'@dosomething/webpack-config'>;
}
declare module '@dosomething/webpack-config/index.js' {
  declare module.exports: $Exports<'@dosomething/webpack-config'>;
}
