# Javascript PHP CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

jobs:
  # Install dependencies & run tests.
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mariadb:10.3
        environment:
          MYSQL_DATABASE: phoenix
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
    steps:
      # Check out source code for this branch & install dependencies.
      # If we can, we'll load these from cache (based on the lockfile).
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            - node-v1-
      - run: npm test
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # Prepare a functional environment so we can run the full application
      # for our browser test suite, and then start simple Laravel server.
      - run:
          name: prepare environment
          command: |
            cp .env.example .env
            php artisan key:generate
            php artisan gateway:key
            php artisan migrate --force
      - run:
          name: start web server
          command: php artisan serve
          background: true
      # Run PHPUnit unit test suite.
      - run: vendor/bin/phpunit
      # Build Javacript application, run ESLint, and Flow type-checker.
      - run: npm run build
      - run: npm run lint
      - run: npm run flow
      # Run our Jest test suite & Cypress browser tests.
      - run: npm run test:ci
      - run: npm run test:browser:ci
